# Generated by Django 3.2 on 2022-12-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221218_0400'),
        ('reviews', '0003_auto_20221218_1130'),
    ]

    operations = [
    ]
